version: '3.8'

services:
  api:
    restart: always
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/code
    ports:
      - '8000:80'
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}

  db:
    restart: on-failure
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'

volumes:
  postgres_data:
  