version: '3.8'

services:
  api:
    restart: always
    depends_on:
      - db
    build:
      context: ./monee-api
      dockerfile: Dockerfile.dev
    volumes:
      - ./monee-api:/code
    ports:
      - '8000:80'
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}

  client:
    restart: always
    build:
      context: ./monee-client
      dockerfile: Dockerfile.dev
    volumes:
      - /code/node_modules
      - ./monee-client:/code
    ports:
      - '3000:3000'

  db:
    restart: on-failure
    image: mysql:8.0.31
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - '3306:3306'

  nginx:
    restart: always
    depends_on:
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '5000:80'

volumes:
  mysql-data:
